import { ContactsDataModel } from 'jbase'

/**
 * 联系人模拟
 */
const ContactsListData: ContactsDataModel[] = [
  { name: '小杰', en_name: '#xiaojie', icon: $r('app.media.avatar1'), code: '1000' },
  { name: '小杰杰', en_name: 'xiaojj', icon: $r('app.media.avatar1'), code: '1001' },
  { name: '小梅子', en_name: 'xiaomz', icon: $r('app.media.avatar2'), code: '1002' },
  { name: '大杰', en_name: 'dajie', icon: $r('app.media.avatar3'), code: '1003' },
  { name: '大杰杰', en_name: 'dajj', icon: $r('app.media.avatar2'), code: '1004' },
  { name: '吕布', en_name: 'lvb', icon: $r('app.media.avatar2'), code: '1005' },
  { name: '貂蝉', en_name: 'diaoc', icon: $r('app.media.avatar2'), code: '1006' },
  { name: '张飞', en_name: 'zhangf', icon: $r('app.media.avatar4'), code: '1007' },
  { name: '关羽', en_name: 'guany', icon: $r('app.media.avatar4'), code: '1008' },
  { name: '刘备', en_name: 'liub', icon: $r('app.media.avatar1'), code: '1009' },
  { name: '诸葛亮', en_name: 'zhugl', icon: $r('app.media.avatar1'), code: '1010' },
  { name: '孙悟空', en_name: 'sunwk', icon: $r('app.media.avatar11'), code: '1011' },
  { name: '猪八戒', en_name: 'zhubj', icon: $r('app.media.avatar8'), code: '1012' },
  { name: '唐僧', en_name: 'tangs', icon: $r('app.media.avatar11'), code: '1013' },
  { name: '花好月圆', en_name: 'hhyy', icon: $r('app.media.avatar5'), code: '1014' },
  { name: 'Jie.', en_name: 'jie', icon: $r('app.media.avatar10'), code: '1015' },
  { name: '太阳之上', en_name: 'sun', icon: $r('app.media.avatar6'), code: '1016' },
  { name: '完美填空', en_name: 'wanm', icon: $r('app.media.avatar7'), code: '1017' },
  { name: '色即是空', en_name: 'sekong', icon: $r('app.media.avatar9'), code: '1018' },
]

export { ContactsListData }