import { ContactsDataModel } from 'jbase'

/**
 * 联系人模拟
 */
const ContactsListData: ContactsDataModel[] = [
  { name: '小杰', en_name: 'AXiao Jie', icon: $r('app.media.avatar1'), code: '1000' },
  { name: '小杰杰', en_name: 'AXiao GG', icon: $r('app.media.avatar10'), code: '1001' },
  { name: '小梅子', en_name: 'AXiao Mz', icon: $r('app.media.avatar2'), code: '1002' },
  { name: '大杰', en_name: 'BDa Jie', icon: $r('app.media.avatar3'), code: '1003' },
  { name: '大杰杰', en_name: 'CDa GG', icon: $r('app.media.avatar13'), code: '1004' },
  { name: '吕布', en_name: 'DLv Bu', icon: $r('app.media.avatar12'), code: '1005' },
  { name: '貂蝉', en_name: 'EDiao Giao', icon: $r('app.media.avatar14'), code: '1006' },
  { name: '张飞', en_name: 'FZhang Fei', icon: $r('app.media.avatar4'), code: '1007' },
  { name: '关羽', en_name: 'Guan Yu', icon: $r('app.media.avatar15'), code: '1008' },
  { name: '刘备', en_name: 'HLiu Bei', icon: $r('app.media.avatar1'), code: '1009' },
  { name: '诸葛亮', en_name: 'IZhu Ge', icon: $r('app.media.avatar12'), code: '1010' },
  { name: '孙悟空', en_name: 'JSun Wu Kong', icon: $r('app.media.avatar11'), code: '1011' },
  { name: '猪八戒', en_name: 'KZhu Ba Jie', icon: $r('app.media.avatar8'), code: '1012' },
  { name: '唐僧', en_name: 'LTang Seng', icon: $r('app.media.avatar16'), code: '1013' },
  { name: '花好月圆', en_name: 'MHua Hao', icon: $r('app.media.avatar5'), code: '1014' },
  { name: 'Jie.', en_name: 'MJie.', icon: $r('app.media.avatar10'), code: '1015' },
  { name: '太阳之上', en_name: 'NSun Up', icon: $r('app.media.avatar6'), code: '1016' },
  { name: '完美天空', en_name: 'OWan Mei', icon: $r('app.media.avatar7'), code: '1017' },
  { name: '色即是空', en_name: 'ZSe Is Empty', icon: $r('app.media.avatar9'), code: '1018' },
]

export { ContactsListData }